// creating an array and passing the number, questions, options, and answers
let questions = [
    {
    numb: 1,
    question: "What is the greenhouse effect?",
    answer: "Certain gases in the atmosphere trap heat and warm the Earth",
    options: [
      "Certain gases in the atmosphere trap heat and warm the Earth",
      "Life on Earth 'exhales' gas that warms up the atmosphere",
      "The tilt of the Earth changes the amount of solar energy the Earth receives",
      "The Sun is putting out more radiant energy over time",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://en.wikipedia.org/wiki/Greenhouse_effect"
    ]
  },
    {
    numb: 2,
    question: "How has the global average temperature changed since the Industrial Revolution?",
    answer: "Warmer by more than 1 degree C (2.1 degrees F)",
    options: [
      "Cooler by 0.1 degree C (0.2 degree F)",
      "Warmer by 0.1 degree C (0.2 degree F)",
      "Warmer by more than 1 degree C (2.1 degrees F)",
      "Warmer by almost 2 degrees C (3.6 degrees F)",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://climate.nasa.gov/vital-signs/global-temperature/ "
    ]
  },
    {
    numb: 3,
    question: "How long does CO2 remain in the atmosphere?",
    answer: "CO2 remains in the atmosphere for up to 200 years, or more.",
    options: [
      "CO2 washes out of the atmosphere seasonally.",
      "CO2 remains in the atmosphere for 5-10 years.",
      "CO2 remains in the atmosphere for up to 200 years, or more.",
      "CO2 remains in the atmosphere permanently",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.theguardian.com/environment/2012/jan/16/greenhouse-gases-remain-air"
    ]
  },
    {
    numb: 4,
    question: "What causes ocean acidification?",
    answer: "CO2 dissolved in ocean water",
    options: [
      "CO2 dissolved in ocean water",
      "Sunscreen in the water",
      "Warm water",
      "Sediment stirred up by extreme storms",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.iucn.org/resources/issues-briefs/ocean-acidification"
    ]
  },
    {
    numb: 5,
    question: "Which of the following is NOT a greenhouse gas?",
    answer: "argon",
    options: [
      "argon",
      "nitrous oxide",
      "methane",
      "carbon dioxide",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://en.wikipedia.org/wiki/Greenhouse_gas"
    ]
  },
  {
    numb: 6,
    question: "The term 'albedo' refers to what property of a surface?",
    answer: "its ability to reflect radiation",
    options: [
      "how long it takes to warm or cool ",
      "its ability to reflect radiation",
      "how fast air flows over it",
      "how much carbon dioxide it can absorb",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://en.wikipedia.org/wiki/Albedo"
    ]
  },
  {
    numb: 7,
    question: "So far, most of the strongest impacts of climate change have been observed in:",
    answer: "Northern latitudes",
    options: [
      "All areas equally",
      "Southern latitudes",
      "The tropics",
      "Northern latitudes",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.greenfacts.org/en/climate-change-ar4/l-3/4-observed-impacts.htm"
    ]
  },
  {
    numb: 8,
    question: "Which renewable energy source contributes the most energy to Canada",
    answer: "Hydro",
    options: [
      "Solar",
      "Hydro",
      "Wind",
      "Geothermal",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.sabic.com/en/collaboration/trend/energy-efficiency?gclid=CjwKCAjwgb6IBhAREiwAgMYKRpuk02AcVArR4sP8_S2MD799pvn-k8c2qK9KXEjwLHLD20JsI8uplxoCPP0QAvD_BwE"
    ]
  },
  {
    numb: 9,
    question: "Which sector emits the most CO2",
    answer: "Energy Production",
    options: [
      "Residential areas",
      "Agriculture",
      "Energy Production",
      "Transport",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.epa.gov/ghgemissions/sources-greenhouse-gas-emissions"
    ]
  },
  {
    numb: 10,
    question: " What percentage of scientists agree that climate change is likely generated by human activities?",
    answer: "97%",
    options: [
      "62%",
      "78%",
      "97%",
      "22%",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://en.wikipedia.org/wiki/Scientific_consensus_on_climate_change#:~:text=Of%20these%2C%2097%25%20agree%2C,greenhouse%20gases%22%20in%20the%20atmosphere."
    ]
  },
  {
    numb: 11,
    question: "One major impact of climate change is increasingly severe storms. Severe storms carry a lot of energy, and it is estimated that for every degree Celsius of warming there is a ___ percent increase in lightning strikes across North America.",
    answer: "12",
    options: [
      "3",
      "12",
      "5",
      "1",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://www.intechopen.com/chapters/39170"
    ]
  },
  {
    numb: 12,
    question: "Measurements of Earth’s gravitational field permit topographic, or surface, mapping of the ocean floor.",
    answer: "True",
    options: [
      "True",
      "False",
      "Both",
      "Neither",
      "To learn more about this question and to get the explanation of the answer, check this link out - https://earthobservatory.nasa.gov/images/87189/seafloor-features-are-revealed-by-the-gravity-field"
    ]
  },
{
  numb: 13,
  question: "How can extreme events like hurricanes, drought, & wildfires impact energy infrastructure?",
  answer: "All of the above",
  options: [
    "Higher gas prices",
    "Water shortages",
    "Power outages",
    "All of the above",
    "To learn more about this question and to get the explanation of the answer, check this link out - https://www.tandfonline.com/doi/full/10.1080/10962247.2017.1401017"
  ]
},
{
numb: 14,
  question: "Why are forests important for mitigating climate change?",
  answer: "Forests serve as a sink in the carbon cycle",
  options: [
    "Trees are an important food source",
    "Leaves of trees reflect all sunlight away from the Earth",
    "Forests serve as a sink in the carbon cycle",
    "Trees provide building materials",
    "To learn more about this question and to get the explanation of the answer, check this link out - https://www.iucn.org/resources/issues-briefs/forests-and-climate-change"
  ]
},


  // you can uncomment the below codes and make duplicate as more as you want to add question
  // but remember you need to give the numb value serialize like 1,2,3,5,6,7,8,9.....

  //   {
  //   numb: 6,
  //   question: "Your Question is Here",
  //   answer: "Correct answer of the question is here",
  //   options: [
  //     "Option 1",
  //     "option 2",
  //     "option 3",
  //     "option 4"
  //   ]
  // },
];